### ISSUE TITLE
GoogleTest Adapter

### ISSUE THREAD

**Issue by OpenNingia** [hbenl/vscode-test-explorer#1]
Hi, I implemented a [GoogleTest ](https://github.com/google/googletest) [adapter](https://github.com/OpenNingia/vscode-google-test-adapter).

Is it ok for you if I publish it on the marketplace?

**Comment by hbenl** [comment]
> Hi, I implemented a GoogleTest adapter.

Great!

> Is it ok for you if I publish it on the marketplace?

Of course that's ok, that's exactly what this extension was made for :)
