### ISSUE TITLE
Support for doctest

### ISSUE THREAD

**Issue by wilhem-meignan** [hbenl/vscode-test-explorer#105]
Hi,

doctest is based on catch but compiles much faster. What is the best way to get doctest to be supported by the Test Explorer UI?

1. Is it possible to configure the "Catch2 and Google Test Explorer" extension so that is recognizes doctest tests?
2. Is it possible to configure doctest so that its tests are recognized just like catch2 tests?
3. If a new test adapter is needed, where is the documentation explaining how to write such an extension? Probably that the "Catch2 and Google Test Explorer" extension would be a good starting point since doctest is based on catch.

Link to doctest: https://github.com/onqtam/doctest

Best Regards,
Will

**Comment by hbenl** [comment]
1. and 2. you'd have to ask the author of the "Catch2 and Google Test Explorer" extension
3. the documentation can be found [here](https://github.com/hbenl/vscode-test-adapter-api)

**Comment by wilhem-meignan** [comment]
@hbenl Thanks for the link. The issue for the "Catch2 and Google Test Explorer" extension is here:
https://github.com/matepek/vscode-catch2-test-adapter/issues/143

**Comment by wilhem-meignan** [comment]
This issue can be closed. Support for doctest has been added to the "Catch2 and Google Test Explorer" extension. Thanks.

https://github.com/matepek/vscode-catch2-test-adapter/issues/143
