### ISSUE TITLE
Feature request: easier multiple build kit test running

### ISSUE THREAD

**Issue by xgdgsc** [hbenl/vscode-test-explorer#106]
https://github.com/matepek/vscode-catch2-test-adapter/issues/145 

In practice I use multiple build kits with cmake and I can' t figure out an easy way to know which I will run from code. Please see the detail in above issue.

**Comment by hbenl** [comment]
Version 2.15.0 will let you pick a test when you click on a code lens for running or debugging multiple tests.

**Comment by xgdgsc** [comment]
Thansk. Is it possible to add quick way to run last. Text like: `Run(last|select) |  Debug(last|select)`
