### ISSUE TITLE
Jest-Cucumber tests not displaying

### ISSUE THREAD

**Issue by Kradirhamik** [hbenl/vscode-test-explorer#108]
Hi,

I'm using jest-cucumber library and although I have tried to set up the Jest configuration, the tests do not display at all.

Can you please check this issue?

**Comment by AlexHaxe** [comment]
I guess this is more an issue for https://github.com/rtbenfield/vscode-jest-test-adapter/issues because vscode-test-explorer only shows what test adapters report.

According to its [README.md](https://github.com/rtbenfield/vscode-jest-test-adapter/blob/master/README.md)

> Currently limited to Jest being available from the ./node_modules/.bin/jest path from the VS Code workspace directory. We are working to make this more flexible.

**Comment by hbenl** [comment]
This issue clearly belongs in the Jest adapter's repository linked above.
