### ISSUE TITLE
Only show the UI when necessary

### ISSUE THREAD

**Issue by Gama11** [hbenl/vscode-test-explorer#109]
It seems that merely having the Test Explorer UI extension installed is enough for the UI to always show up in the sidebar (even if you have no test adapters installed at all, or if you are in a workspace where no test adapters activate):

![](https://i.imgur.com/2TWV0my.png)

I think it would make sense to make this context-sensitive, so that the UI is only shown once a test adapter has been registered. This can be done with a `when` condition on the view in `package.json` checking a custom context key such as `testExplorerActive`. Context keys can be set like this: https://stackoverflow.com/a/44893369/2631715

**Comment by hbenl** [comment]
Implemented in version 2.16.0.

**Comment by Gama11** [comment]
Hm... the way this has been implemented actually seems problematic for the Haxe test adapter I help maintain. We don't dynamically discover tests "upfront", but during compilation. So we don't know about tests until "Run all tests" has been run at least once (and the "run" button for that is now no longer visible by default because the view doesn't exist yet). That's why I originally suggested that the visibility of the view should be tied to a test adapter _registering_ itself.

Not sure if any other test adapters suffer from this problem.

**Comment by hbenl** [comment]
> That's why I originally suggested that the visibility of the view should be tied to a test adapter registering itself.

Hmm, I think most test adapters always register themselves immediately, so the view would only get hidden when you have no adapters *installed* - I think that would be rather pointless because why would anyone install Test Explorer without any adapters?

> Not sure if any other test adapters suffer from this problem.

Good question. I have designed the Test Explorer so that you can add tests and suites during a test run because I knew that some test frameworks make it hard (or even impossible) to discover tests upfront, but this is the first time I hear about an adapter that actually uses this capability.

You can get the old behavior back by setting `testExplorer.hideWhenEmpty` to `false` (which I mentioned in the Changelog but forgot to add to the Readme).
But your users would probably get confused if they have to add this setting to be able to use your adapter. So I guess I should change the default for the setting to `false`, right?

**Comment by Gama11** [comment]
>Hmm, I think most test adapters always register themselves immediately, so the view would only get hidden when you have no adapters _installed_.

That's only the case when the test adapter has poor activation events / `*`. The Haxe test adapter only activates / registers itself in Haxe projects: https://github.com/vshaxe/haxe-test-adapter/blob/master/package.json#L50

**Comment by hbenl** [comment]
OK, so there should be 3 ways to configure this:
* always show the Test Explorer
* show it only when at least one adapter registered itself
* show it only when at least one adapter registered itself *and* it found some tests

I'll implement this tomorrow.

**Comment by Gama11** [comment]
With the second option being the default setting? :)

**Comment by kondratyev-nv** [comment]
It looks like right now `"testExplorer.hideWhenEmpty"` option breaks Test Explorer usage for the users, see https://github.com/hbenl/vscode-test-explorer/issues/113 and https://github.com/kondratyev-nv/vscode-python-test-adapter/issues/125. Are there any plans on fixing it?

**Comment by hbenl** [comment]
> With the second option being the default setting? :)

That was my initial plan, but now I realized that some adapters are only activated when the user opens the Test Explorer view, so the first option needs to be the default.

**Comment by Gama11** [comment]
Hm, I would consider that a bug though - if that's the only activation event, commands like "Run all tests" would fail to work before the user has opened the view.

@kondratyev-nv You should probably activate on the various test explorer commands [like we do for the Haxe test adapter](https://github.com/vshaxe/haxe-test-adapter/blob/master/package.json#L50) as well.

**Comment by hbenl** [comment]
@Gama11 But even if all adapters activated on the Test Explorer commands, hiding the Test Explorer until an adapter is registered (and hence until a Test Explorer command is invoked from the palette or a keybinding) would still be confusing.

**Comment by Gama11** [comment]
Yes, I guess it only works well for adapters that also activate on a language or similar.

**Comment by hbenl** [comment]
Version 2.17.0 changes the default back to the old behavior (never hide the Test Explorer) and adds the option to hide it when no adapters have been registered or when the registered adapters found no tests.
