### ISSUE TITLE
Go to source doesn't work with absolute windows paths

### ISSUE THREAD

**Issue by melak47** [hbenl/vscode-test-explorer#11]
When the file for a test case or suite is given as an absolute windows path, e.g. `d:\src\test.cpp`, `fileToUri` in `util.ts` parses it as an URI with scheme "d" instead of a file path, which then can't be opened.

A workaround could be:
```ts
const schemeMatcher = /^[a-z][a-z0-9+-.]*:/;
const winpathMatcher = /^[a-zA-Z]:\\/;
export function fileToUri(file: string): vscode.Uri {
	if (!winpathMatcher.test(file) && schemeMatcher.test(file)) {
		return vscode.Uri.parse(file);
	} else {
		return vscode.Uri.file(file);
	}
}
```

This should work as long as no test adapter produces absolute paths with forward slashes on windows...

**Comment by hbenl** [comment]
I went for an even simpler workaround: I changed the `schemeMatcher` to require URL schemes to have at least 2 characters (I've never seen a scheme with just one character). I'll publish when the marketplace is back online.
Thanks for reporting this.
