### ISSUE TITLE
Option to disable codelens above tests not working

### ISSUE THREAD

**Issue by jonstrutz11** [hbenl/vscode-test-explorer#111]
I am trying to disable the codelens ("Run Test | Debug Test") entries above each test (I'm using pytest).

I set testExplorer.codeLens to False in my settings.json:
![image](https://user-images.githubusercontent.com/23544847/73575364-a6c76280-443d-11ea-94bd-62877b533a3e.png)

However, the codelens entries remain above each test, even if I restart VS Code or rediscover tests:
![image](https://user-images.githubusercontent.com/23544847/73575339-9911dd00-443d-11ea-858c-b5b865c800c1.png)

I tested this in a simple project where app.py is empty and test_app.py and settings.json are as above:
<pre>
├── .vscode
   ├── settings.json
├── app
   ├── app.py
   ├── tests
       ├── test_app.py
</pre>

Some other information:
- OS: Windows 10
- VS Code: 1.41.1
- Test Explorer UI: 2.15.0

Let me know if you can reproduce and/or need any other info from me, and thank you for the great extension - I really enjoy using it.

**Comment by jonstrutz11** [comment]
Also, just in case it is useful, if I add `"editor.codeLens": false` to my settings.json, they all disappear.

**Comment by hbenl** [comment]
The code lenses that you see ("Run Test | Debug Test") are not from this extension (it produces code lenses "Run | Debug | Show in Test Explorer"). I guess that they are from Microsoft's Python extension, which doesn't use this extension to display the tests (even though the documentation talks about it using a "Test Explorer", but that seems to be their own implementation).
