### ISSUE TITLE
Test Explorer is hidden when it shouldn't

### ISSUE THREAD

**Issue by matepek** [hbenl/vscode-test-explorer#113]
I've reverted to the version 2.15. It is good, but in case of the new version 2.16 I don't see the Test Explorer button on the Activity Bar (left column). Therefor I'm unable to activate the extension and use it.

(The changes relates to: https://github.com/hbenl/vscode-test-adapter-api/issues/7)

**Comment by matepek** [comment]
Setting `"testExplorer.hideWhenEmpty": false` solves the problem, but according to the documentation `"Hide the Test Explorer when no tests have been found"` it should be shown because tests have been found.

**Comment by matepek** [comment]
In case of 2.15: When I open the vscode my tests are not parsed at that time but when I click to the Test Explorer icon on the Activity Bar. So before I do that my extension considered not to have tests. I guess this causes the issue.

**Comment by kondratyev-nv** [comment]
Same here, it looks like test adapters are not even initialized.

**Comment by hbenl** [comment]
I'm terribly sorry, I made a wrong assumption in yesterday's update. Working on a fix right now.

**Comment by hbenl** [comment]
Version 2.17.0 changes the default back to the old behavior (never hide the Test Explorer) and adds the option to hide it when no adapters have been registered or when the registered adapters found no tests.

**Comment by kondratyev-nv** [comment]
Thank you for the quick fix!
