### ISSUE TITLE
Keyboard shortcut to view full error message

### ISSUE THREAD

**Issue by brianlow** [hbenl/vscode-test-explorer#117]
Ruby test failures are often multi-line. Only the first line is shown:
![image](https://user-images.githubusercontent.com/938138/75855352-4fefd880-5daf-11ea-886b-da7762a94dc6.png)

Notice we can't see the actual value. 

Would like a command to view the full message

**Comment by hbenl** [comment]
When you click on the failed test in the Test Explorer, the log panel will be opened showing the full error message for that test. Furthermore, there should be a Code Lens "Show Log" above failed tests that you can click to show the log panel.

**Comment by brianlow** [comment]
Can this be done with the keyboard?

Looking for a fast test, fix, re-test loop during development.

**Comment by hbenl** [comment]
Once you have opened the log panel by clicking on the test in the Test Explorer or clicking the "Show Log" code lens, the log panel will be updated every time you run that test, so that should be perfect for a fast test, fix, re-test loop.
