### ISSUE TITLE
Allow test-explorer.reveal command argument to be a string (id or path)

### ISSUE THREAD

**Issue by Nic007** [hbenl/vscode-test-explorer#118]
Right now, if you try to execute this command  like this:

`vscode.commands.executeCommand('test-explorer.reveal', 'idForTestOrSuite');`
or
`vscode.commands.executeCommand('test-explorer.reveal', 'pathtoFileWithTests');`

You won't have any success. The parameter expected is a tree view node that is unaccessible from an outside scope. (Or if you know how to access them from at least an adapter...)

**Comment by hbenl** [comment]
I have added the ability to pass the ID of a test or suite to the `test-explorer.reveal` command in version 2.18.0. I hope this is good enough, if you have the path to a test file maybe you could find the ID of the corresponding suite node yourself.
