### ISSUE TITLE
Output panel should not toggle on test runs

### ISSUE THREAD

**Issue by harmon** [hbenl/vscode-test-explorer#122]
When using any of the "Test Explorer: Run *" commands, if the Output panel that shows the test errors is open, it will momentarily close, and once the tests are done, reopen. It has the effect of shifting all open panes back and forth.

Ideally it would not close the open Output section, and just refresh it once the tests have finished.

**Comment by sleighsoft** [comment]
You can configure that in the settings I believe.

**Comment by hbenl** [comment]
Yes, you can configure it with the `testExplorer.hideEmptyLog` setting.
