### ISSUE TITLE
Enable autorun is failed

### ISSUE THREAD

**Issue by svak** [hbenl/vscode-test-explorer#128]
OS `Ubuntu 18.04.4`

Visual Studio Code:
```
    Version: 1.44.0
    Commit: 2aae1f26c72891c399f860409176fe435a154b13
    Date: 2020-04-08T11:22:13.689Z
    Electron: 7.1.11
    Chrome: 78.0.3904.130
    Node.js: 12.8.1
    V8: 7.8.279.23-electron.0
    OS: Linux x64 5.3.0-46-generic snap
```

1. Select "Enable autorun" from top menu (Test Explorer view)
2. Error is appeared as popup window: `Running the contributed command: "test-explorer.enable-autorun" failed`

I believe that error was introduced with latest update. Because before that that function is working fine.

**Comment by hbenl** [comment]
This is due to a change (possibly a bug) in VS Code: Microsoft/vscode#94872

**Comment by hbenl** [comment]
I have added a workaround for this to version 2.18.0.

**Comment by svak** [comment]
Thanks!
