### ISSUE TITLE
Missing GO tests when in remote

### ISSUE THREAD

**Issue by arcadien** [hbenl/vscode-test-explorer#135]
Issue Type: <b>Bug</b>

When remote-coding my Go code, tests does not appear in the tree. 
Coding locally, tests appear.

Extension version: 2.18.0
VS Code version: Code 1.45.0 (d69a79b73808559a91206d73d7717ff5f798f23c, 2020-05-07T16:18:48.860Z)
OS version: Windows_NT x64 10.0.18363
Remote OS version: Linux x64 5.4.0-29-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.97GB (5.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: Sentryo|
|OS|Linux x64 5.4.0-29-generic|
|CPUs|Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz (4 x 3400)|
|Memory (System)|3.84GB (2.12GB free)|
|VM|100%|
</details>

**Comment by matepek** [comment]
This is probably relates to [this extension](https://gitlab.com/firelizzard/vscode-go-test-adapter.git). Please close it here if you agree and reopen it there. This extension just provides the UI interface.

**Comment by arcadien** [comment]
Thanks. Forwarded the ticket.
Regards,
