### ISSUE TITLE
Feature request: Populate Problems panel with failing tests

### ISSUE THREAD

**Issue by emilyst** [hbenl/vscode-test-explorer#136]
I would find it very useful if the Test Explorer UI also populated the Problems panel with test failures. This would allow me to see all test failures in one place.

Thanks in advance.

**Comment by matepek** [comment]
Interesting idea. I think I agree.
Meanwhile, check [this](https://marketplace.visualstudio.com/items?itemName=connorshea.vscode-test-explorer-status-bar)

**Comment by emilyst** [comment]
> Interesting idea. I think I agree.
> Meanwhile, check [this](https://marketplace.visualstudio.com/items?itemName=connorshea.vscode-test-explorer-status-bar)

Thank you for the suggestion. I have seen that, but it lacks some functionality. For example, it won't show the actual failures, nor can I navigate to the failure from it.

**Comment by emilyst** [comment]
It looks like this would be a matter of providing a "diagnostic": https://code.visualstudio.com/api/language-extensions/programmatic-language-features#provide-diagnostics.

There are samples available:

* https://github.com/microsoft/vscode-extension-samples/blob/master/code-actions-sample/src/diagnostics.ts
* https://github.com/microsoft/vscode-extension-samples/tree/master/diagnostic-related-information-sample

**Comment by emilyst** [comment]
I've not used TypeScript or written a VS Code extension before, but I decided to see if I could try my hand at a TestController extension that would do this without having to modify the Text Explorer itself.

It almost works! Find that here: https://github.com/emilyst/vscode-example-test-controller/blob/master/src/controller.ts.

I could get it all of the way, but unfortunately, the particular test adapter I'm using (for Ruby) does not populate the information I need (getting even just the filename was a slight hack). I could possibly submit a pull request to fix that over on that test adapter.

Anywho, point being—it's possible. Not sure if it belongs in a separate extension, but it's theoretically feasible.

**Comment by AlexHaxe** [comment]
@emilyst I might have it wrong, but it seems like file and line number info is not present in the `testEvent` object. I used haxe-test-adapter on a repro test project which usually has position info, so I guess it needs a fix in test explorer or the protocol.

**Comment by emilyst** [comment]
> @emilyst I might have it wrong, but it seems like file and line number info is not present in the `testEvent` object. I used haxe-test-adapter on a repro test project which usually has position info, so I guess it needs a fix in test explorer or the protocol.

In fact, the [TestEvent may have a file and line number](https://github.com/hbenl/vscode-test-adapter-api/blob/105f6b453e9900a10549e4e60c6d74e84a9fee14/src/index.ts#L313-L323), as may [its TestDecorations](https://github.com/hbenl/vscode-test-adapter-api/blob/105f6b453e9900a10549e4e60c6d74e84a9fee14/src/index.ts#L328-L338). Therefore it is a question of [the TestAdapter populating the events which it emits](https://github.com/hbenl/vscode-example-test-adapter/blob/master/src/adapter.ts#L56).

I suspect it's the case that I could write a test controller extension such that populates diagnostics when the needed information is present and otherwise does not when it is absent.

**Comment by hbenl** [comment]
That is indeed an interesting idea. It could be added to this extension, but it could also serve as a good example for a TestController. Would you be willing to maintain such an extension? If so, I could help out with a few PRs.

> Therefore it is a question of the TestAdapter populating the events which it emits.

Actually the `file`/`line` properties in the events should only be populated if the adapter wants to _change_ that information. If these properties are not set, a Test Controller should take them from the info sent with the last `TestLoadFinishedEvent`.

**Comment by emilyst** [comment]
> That is indeed an interesting idea. It could be added to this extension, but it could also serve as a good example for a TestController. Would you be willing to maintain such an extension? If so, I could help out with a few PRs.

That sounds fine to me. I haven't really polished what I have. I just wanted to prove it's possible.

> > Therefore it is a question of the TestAdapter populating the events which it emits.
> 
> Actually the `file`/`line` properties in the events should only be populated if the adapter wants to _change_ that information. If these properties are not set, a Test Controller should take them from the info sent with the last `TestLoadFinishedEvent`.

I found this out [when I tried it](https://github.com/connorshea/vscode-ruby-test-adapter/pull/49#issuecomment-629033443). But I assume the `TestDecoration` is designed for this purpose?

Or is it better to store away failures during failed `TestEvent`s and then populate the diagnostics on `TestLoadFinishedEvent`?

To populate the diagnostics, I need to know when errors occur, where they occur, and what the error is. (And I need to be able to clear them at the appropriate time.)

**Comment by emilyst** [comment]
I took another swing and feel like I've gotten a good bit closer to working, but not 100% there. I'll probably look more at this in the next few days.

![](https://drop.emily.st/Capture%202020-05-16%20at%2022.13.33.png)

You're welcome to check out [what I did over here](https://github.com/emilyst/vscode-example-test-controller/commit/4064368d8ddecc31e044bd6d7504a6cbbd59eb9b).

**Comment by matepek** [comment]
Hello @emilyst ,
I'm happy that you are working on this, it seems a cool stuff.

I would like to draw your attention to the following [configs](https://github.com/hbenl/vscode-test-explorer#configuration):
`testExplorer.gutterDecoration`, `testExplorer.errorDecoration`, `testExplorer.errorDecorationHover`.
I think using your extension will replace those functionalities so I would disable it for development to get a clearer picture.

What I'm not sure about how will I recognize and handle multiline assertions. This is currently not supported by `TestDecoration`. @hbenl what do you think about adding something analog to [vscode.Range](https://code.visualstudio.com/api/references/vscode-api#Range)?

It could be an alternative of `file` and `line` properties with backward compatibility.

**Comment by emilyst** [comment]
> Hello @emilyst ,
> I'm happy that you are working on this, it seems a cool stuff.

I'm glad to help.

> I would like to draw your attention to the following [configs](https://github.com/hbenl/vscode-test-explorer#configuration):
> `testExplorer.gutterDecoration`, `testExplorer.errorDecoration`, `testExplorer.errorDecorationHover`.
> I think using your extension will replace those functionalities so I would disable it for development to get a clearer picture.

I think the primary problem my extension would solve is that it would be possible to see _all_ test failures in a single place rather than having to navigate to each. So in that way, I don't know if they're replacements for the existing functionality.

**Comment by matepek** [comment]
What I meant that both the current solution and TestDecoration provides highlight and hover.
I probably wont use it together and I will turn off the mentioned features. Your screenshot contains both and it looks i slightly overwhelmed for me. But this is just my personal preference.

**Comment by emilyst** [comment]
> What I meant that both the current solution and TestDecoration provides highlight and hover.
> I probably wont use it together and I will turn off the mentioned features. Your screenshot contains both and it looks i slightly overwhelmed for me. But this is just my personal preference.

Ah, sure. It's a bit busy.

**Comment by emilyst** [comment]
> What I'm not sure about how will I recognize and handle multiline assertions. This is currently not supported by `TestDecoration`. @hbenl what do you think about adding something analog to [vscode.Range](https://code.visualstudio.com/api/references/vscode-api#Range)?
> 
> It could be an alternative of `file` and `line` properties with backward compatibility.

Even discovering where it happens, when it's a single line, is not a problem I've solved completely.

As I mentioned on the commit in a comment, the TestDecoration's documentation for the `file` field [discourages setting it the `file` field](https://github.com/hbenl/vscode-test-adapter-api/blob/master/src/index.ts#L333-L338). And the `file` field on the `TestEvent` event does not communicate where the event was but [rather where it should be _relocated_](https://github.com/hbenl/vscode-test-explorer/issues/136#issuecomment-629683700), making it useless for my purposes.

This is tough. From the point of view of a controller looking at a `TestEvent`, how should I know definitively where that event took place?

**Comment by matepek** [comment]
It is discouraged if the TestInfo's `file` field is the same as the TestDecoration's `file` field. (and you have the TestInfos from the `TestLoadEvent`)

**Comment by matepek** [comment]
The `file` in the `TestDecoration` should override (if present) the file of the `TestInfo`. And **DO NOT** assume that they are always the same.

**Comment by emilyst** [comment]
> The `file` in the `TestDecoration` should override (if present) the file of the `TestInfo`. And **DO NOT** assume that they are always the same.

Got it.

**Comment by emilyst** [comment]
> It is discouraged if the TestInfo's `file` field is the same as the TestDecoration's `file` field. (and you have the TestInfos from the `TestLoadEvent`)

Okay, let me see if I got this right. I think I need to be listening to two kinds of events.

1. Listen for `TestLoadFinishedEvent` events.
    * Recurse into `TestLoadFinishedEvent.suite?.children?` to find all the `TestInfo` objects. Store those. (Maybe put them into a `Map<string, TestInfo>` where the key is the `TestInfo.id` field.)
    * Delete any diagnostics I've previously created if no `TestInfo` object exists for it.
3. Listen for failing `TestEvent` events.
    * When the a failing `TestEvent` event occurs, find the `TestInfo` object in my Map.
    * Create a diagnostic at the location using either
        * the `TestDecoration` fields on the `TestEvent` event (if present), or
        * the `TestInfo` object if not.

**Comment by matepek** [comment]
1. And children of children. And children of children of children. You have to traverse a tree and collect all the leafs with `type == 'test'`.
  Storing like that seems good.

2. Not just the failing but all test events. And you have to update the problems accordingly. When a tests passes I guess the `decoraiton`'s usually empty but don rely on the test result just remove the old problems and add the new ones regardless of the test's `state`. (The problem's severity could depend on the `state`. So if it is passed I would put all the `decorations` as info.)
  Rephrased: "Create a diagnostic at the locations contained by `decorations` using line and if file is present then that file or the `TestInfo`'s file otherwise with the `TestDecoration`'s line".

**Comment by emilyst** [comment]
> * And children of children. And children of children of children. You have to traverse a tree and collect all the leafs with `type == 'test'`.
>   Storing like that seems good.

Right. I had meant to imply that by "recurse."

> * Not just the failing but all test events. And you have to update the problems accordingly. When a tests passes I guess the `decoraiton`'s usually empty but don rely on the test result just remove the old problems and add the new ones regardless of the test's `state`. (The problem's severity could depend on the `state`. So if it is passed I would put all the `decorations` as info.)
>   Rephrased: "Create a diagnostic at the locations contained by `decorations` using line and if file is present then that file or the `TestInfo`'s file otherwise with the `TestDecoration`'s line".

Of course, you're right. But this sounds like the right track. I can just do this.

**Comment by matepek** [comment]
we don't have column information currently, but hopefully in the future. Meanwhile I think you could select the whole the line with range like this:
```
const file = '..';
const line = X;
const r = new Range(line, 0, line, 999)
```
Haven't tried I assume it will work

**Comment by emilyst** [comment]
Pushed [a new commit](https://github.com/emilyst/vscode-example-test-controller/commit/a302ea797d40bd836438e5cc8beaf590710e0087) based on the discussion above. [Here's the whole set of changes compared against the base example extension.](https://github.com/hbenl/vscode-example-test-controller/compare/master...emilyst:master) It works pretty great here so far.

![](https://drop.emily.st/Capture%202020-05-17%20at%2022.27.01.png)

A few rough things to clean up before I'd consider this ready.

* Ensure user can set which severities for which they want to populate diagnostics. (Right now, it's hardcoded only to populate failures as errors. Can also add skipped tests as warnings, passing tests as infos.)
* Figure out the idiomatic way to deal with all the possibly undefined variables. I am sure that `if (typeof x !== 'undefined') { /* do thing */ }` is not the right thing, but this is my first time using TypeScript or JavaScript.
* Fill out more attributes on the diagnostics than what's available just in the constructor.
* Maybe a few other stylistic sundries. 
* Prepare plugin for release by updating license, name of repository, README, etc.

**Comment by emilyst** [comment]
I've decided to continue the work over here: https://github.com/emilyst/vscode-test-explorer-diagnostics.

I've published the first alpha version of this extension here: https://marketplace.visualstudio.com/items?itemName=emilylilylime.vscode-test-explorer-diagnostics.

**Comment by emilyst** [comment]
The above extension effectively resolves the issue for me, so I think I'll close this. Please leave further discussion on [its repo](https://github.com/emilyst/vscode-test-explorer-diagnostics) as issues.

(There are a handful of known issues yet to be addressed in it. The README mentions several:

- Handle retired test states fully.
- Add preferences for which severity of diagnostics to provide.
- Add suggestions for preferences in Test Explorer to set.
- Discover proper ranges to provide diagnostics.
- Custom extension icon.

I also know I need to update a diagnostic when the underlying test has been moved.)
