### ISSUE TITLE
[Request] Ability to exclude/include test files manually

### ISSUE THREAD

**Issue by miojoffey** [hbenl/vscode-test-explorer#137]
I would like to request that somehow auto-detection of tests files be optional and the ability to manually exclude/include test files. 
I am using pytest, but somehow it gets all the tests from other 3rd party libraries as well which i do not want. I only want specified test files on my test explorer, but my test explorer is bombarded with so many tests files that I do not want.

**Comment by matepek** [comment]
Hello, I think you should as the author of the Python test explorer which is based on this extension. [This](https://github.com/kondratyev-nv/vscode-python-test-adapter) is it,right?

**Comment by miojoffey** [comment]
Hi, I think this would be great if we can somehow right click a test file and exclude them with a context menu. Anyways, I was able to solve this issue using the PyTestArgs settings on vscode. Used --ignore args to exlcude those files and folders not needed.
