### ISSUE TITLE
[Question] There is a way to put messages in Test Explorer Output? 

### ISSUE THREAD

**Issue by danielmeza** [hbenl/vscode-test-explorer#145]
I wonder if there is any way to put a custom message in the test explorer, this is useful for trace what happen in the test code, for example in Visual Studio we use the Trace.WriteLine and all that output is show in the test result detail.

**Comment by matepek** [comment]
Hey, I' not sure what do you mean by custom message. You can add any message to output window through events. If you thinking adding diagnostic messages here is a solution:
https://github.com/hbenl/vscode-test-adapter-util/blob/master/src/log.ts

**Comment by danielmeza** [comment]
Hi @matepek sorry if I not explain my self well, what I means is to write a simple console log inside a test case and see that log related to the execution of a test.

**Comment by hbenl** [comment]
> write a simple console log inside a test case and see that log related to the execution of a test.

This is possible if the Test Adapter implements it.
For example, the Mocha Test Adapter will [read all messages](https://github.com/hbenl/vscode-mocha-test-adapter/blob/b3f3d4d341467bb8151de4839cd70083a57e5c2a/src/core.ts#L294) from `stdout` and `stderr` and write them [to its own output channel](https://github.com/hbenl/vscode-mocha-test-adapter/blob/b3f3d4d341467bb8151de4839cd70083a57e5c2a/src/core.ts#L281) (which is used to collect the output from _all_ tests) as well as [send them to Test Explorer](https://github.com/hbenl/vscode-mocha-test-adapter/blob/b3f3d4d341467bb8151de4839cd70083a57e5c2a/src/core.ts#L284) in events so they can be shown in Test Explorer's output channel (which always shows the output from _one_ test).
