### ISSUE TITLE
Turning off verbose logs

### ISSUE THREAD

**Issue by meelash** [hbenl/vscode-test-explorer#147]
All of a sudden (not sure when the change happened), in the Test Explorer Output I'm getting very verbose logs. It's actually kinda nice for debugging, but I'd like to be able to turn it off, too. We're talking very verbose, so it is slowing down my machine! Can't figure out if it is a setting in test explorer or log4js, or some other package I'm using. Any help would be appreciated!

Examples:
At first I thought it must be a setting that got switched on in knex.js:
![Screen Shot 2020-07-06 at 4 40 39 PM](https://user-images.githubusercontent.com/59001/86639755-744f0200-bfa7-11ea-87b8-66bf64643124.png)
But, then I noticed nock also giving verbose logs:
![Screen Shot 2020-07-06 at 4 41 18 PM](https://user-images.githubusercontent.com/59001/86639808-8cbf1c80-bfa7-11ea-867d-c2ace4eb95c7.png)
Even log4js seems to be spitting out it's own verbose debugging logs (rather meta to see the logs about the production of the log that's coming up!):
![Screen Shot 2020-07-06 at 4 42 06 PM](https://user-images.githubusercontent.com/59001/86639945-cdb73100-bfa7-11ea-936e-9559cf4742ff.png)

Any tips would be appreciated.

**Comment by hbenl** [comment]
The Test Explorer log simply shows all log messages that it receives from the Test Adapter for your testing framework, there are no "log levels" for these messages, so Test Explorer can't decrease verbosity, it can only show everything or nothing.
So this needs to be fixed either in the Test Adapter (please open an issue there) or in your project's logging settings.
