### ISSUE TITLE
[phpunit] Running single tests result in "No tests executed!"

### ISSUE THREAD

**Issue by carestad** [hbenl/vscode-test-explorer#149]
Installed version: PHPUnit Test Explorer v2.0.74

Recently I have had issues running single tests in my test classes. They always result in the same error – `No tests executed!`.

![image](https://user-images.githubusercontent.com/65263/87354532-f8ccf200-c55e-11ea-96f3-3ce54424b620.png)

Running all tests in a whole test class works though.

![image](https://user-images.githubusercontent.com/65263/87354597-1ac67480-c55f-11ea-8a4a-8bb5ed5c276c.png)

Rolling back to version 2.0.72 fixes this issue.

**Comment by AlexHaxe** [comment]
vscode-test-explorer only visualises what vscode-phpunit reports, so it's vscode-phpunit's responsibility to detect and execute tests and report results back to test explorer (which knows nothing about phpunit or any other concrete test framework).

I think you might have more luck finding a fix over here (as soon as there is a fix): https://github.com/recca0120/vscode-phpunit/issues/64

**Comment by carestad** [comment]
:facepalm: I must have clicked the wrong extension's `Repository` link in VSCode for some reason. Sorry for the mixup and thanks for the quick reply!
