### ISSUE TITLE
Suggestion: Go to test source on double click

### ISSUE THREAD

**Issue by drstrangelug** [hbenl/vscode-test-explorer#156]
One feature of Eclipse's Junit view is that double clicking on a test takes you straight to the source for that test.

Could we have that option please, or even a defined behaviour for double click ( go to source/run/debug).

**Comment by Trass3r** [comment]
Makes sense.
1 click => test output, double-click => source.

https://github.com/hbenl/vscode-test-explorer/blob/3a4f40d7c6251fe0b3fca171326325a4a50e389b/src/tree/testNode.ts#L189-L193

https://github.com/microsoft/vscode/issues/39601#issuecomment-376415352
