### ISSUE TITLE
python.pythonPath is being deprecated. This change breaks test-explorer

### ISSUE THREAD

**Issue by dfioravanti** [hbenl/vscode-test-explorer#157]
Microsoft announced that they will slowly deprecate `python.pythonPath` in https://devblogs.microsoft.com/python/python-in-visual-studio-code-may-2020-release/ and specifically the section "Coming Next: moving python.pythonPath out of settings.json". The rational behind it is explained in microsoft/vscode-python#2125

For work we need this feature so I manually activate it and it breaks test-explorer. Right now test-explorer defaults to the standard python environment when I run or debug the tests. 

In vscode-restructuredtext/vscode-restructuredtext/issues/222 is it possible to see how another extension that depended on `python.pythonPath` fixed the problem.

**Comment by AlexHaxe** [comment]
please report an issue here: https://github.com/kondratyev-nv/vscode-python-test-adapter/issues

see also: https://github.com/hbenl/vscode-test-explorer/issues/155

**Comment by dfioravanti** [comment]
Ops, I did not realized how the extension works. Thanks =)
