### ISSUE TITLE
Q/R: How can I mark the result of the tests outdated?

### ISSUE THREAD

**Issue by matepek** [hbenl/vscode-test-explorer#16]
Hello,

Here is the situation:
- User runs the tests Some of them fails, some of them succeeds.
- User recompile the executable.
Now we don't know about the tests anything because all tests(contained by the executable) could be changed. (Also new tests created and old ones deleted, renamed.)

Most of the cases are straight forward except when the adapter can find a test with the same name.
This case I would like to mark the test obsoleted(so all the old ones which haven't been deleted.) and also would like to still show the last valid result of the test.

Can I do that now? I'm asking, because I've noted that sometimes The tests are greyed out, but I'm not sure when. That actually could be a solution.
Or new states maybe. (for example: failedOutdated, passedObsoleted)

Best Regards,
Mate

**Comment by hbenl** [comment]
Yes, this is already possible by adding `"testExplorer.onReload": "retire"` to your settings (I use the word "retire" to mean "mark as outdated"). It should work exactly as you describe (showing the old state of tests that were not deleted greyed out). You can also manually mark them as outdated by choosing "Retire test states" from the context menu.

**Comment by hbenl** [comment]
> I can see that retire is de default.

?? No, it's not the default, you have to set `"testExplorer.onReload": "retire"` explicitly in your settings.

> `$ touch testexecutable`

have you verified that this triggers a reload of your tests? The Test Explorer retires the test states when it receives the `TestLoadFinishedEvent`. If you're sure that event is fired and the tests are still not retired, could you create a little test project that I could use to reproduce the problem (I have some C++ experience, but that was many years ago...)?

**Comment by matepek** [comment]
You are right it is not default, sorry. VSCode  new 'Settings page'  shows me this:
<img width="662" alt="screen shot 2018-10-07 at 16 01 04" src="https://user-images.githubusercontent.com/16504598/46582647-74287800-ca4a-11e8-980c-8d4f9f92d47b.png">
This was mislead me. Now I can see that the tests retire. 

But..
I've just noticed, that it retires all of my tests, not just the changed branch but all.
Example:
- testexecutable1
  - test 1-1
  - test 1-2
-testexecutable2
  - test 2-1
In case of this if I touch testexecutable1 also testexecutable2 will be retired.

This is because I reload testexecutable2 and send the TestLoadFinishedEvent event.
Should I do something differently?

**Comment by matepek** [comment]
Oh yeah, I can see now the description says that it will do that, so it's normal. :)
Then I'm just saying, It would be nice to only retire the relevant ones.

**Comment by hbenl** [comment]
Wow, that *is* misleading. Even worse, for me it shows different "defaults" (I have no idea where these come from):
![screenshot_2018-10-07_16-28-00](https://user-images.githubusercontent.com/16060807/46582870-1138e000-ca4e-11e8-803a-0470cf7dde04.png)

> It would be nice to only retire the relevant ones.

Yeah, that would be possible if adapters could do a "partial reload", i.e. they only send those tests in the `TestLoadFinishedEvent` that they reloaded and tell the explorer to merge those with the other tests. Then the Test Explorer would know which tests were reloaded and which weren't. This is already on my todo list.

**Comment by matepek** [comment]
Me neither. Thats the only things in my config files.
```
  // Retire or reset all test states whenever the test tree is reloaded
  "testExplorer.onReload": "",

  // Retire or reset all test states whenever a test run is started
  "testExplorer.onStart": ""
```

Maybe because you haven't set any "default" in your package.json and "retire" is the first enum value.
