### ISSUE TITLE
How can I see output of tests?

### ISSUE THREAD

**Issue by daramasala** [hbenl/vscode-test-explorer#17]
I would like to see all the output of the test (stderr and stdout).
This is useful for example:
* When comparing arrays, chai prints the actual and expected values. I couldn't find a way to see this in Test Explorer
* When a test throws an exception it is valuable to see the stacktrace of the exception

I tried checking the `OUTPUT` tab of Test Explorer but nothing is printed there.

**Comment by hbenl** [comment]
It is up to the Test Adapters to provide this information:
* Some adapters provide output for individual tests (usually only failed tests, providing e.g. a stacktrace) - when you click on a (failed) test and the Adapter provided that information, an Output channel will be opened showing that information
* Some adapters create their own output channel and pipe stdout to it (e.g. the Jasmine Adapter does this)
Please create an issue in the repository for the Test Adapter that you are using.
