### ISSUE TITLE
Duplicate tests are created when describe blocks are found while running tests (e.g. describe.each)

### ISSUE THREAD

**Issue by TheSench** [hbenl/vscode-test-explorer#177]
When running tests that contain a Jest `describe.each` block, the adapter is unable to determine the exact `describe` or `test` blocks up front.  Due to this, it will discover them when running the test and add them to the suite.

When the adapter sends the `suite` events for the describes and tests, if it the event for the `describe` block has children in it, they get converted to `TreeNodes` underneath the `TestSuiteNode` for the `describe` block, but do not get added to `nodesById`.  When the `suite` events for the tests come in, since they don't exist in `nodesById` yet, they get added to `nodesById` _and_ to the parent `describe` block's `TestSuiteNode` ( a second time).

### Initial Tests (note: `describe.each` doesn't show yet up because of missing support in Jest test adapter)
![image](https://user-images.githubusercontent.com/9260413/103477665-0b4a1a80-4d8f-11eb-8f8c-cfea48373ac8.png)

### Discovered Tests (note duplicate `"test test inside describe.each 1"`)
![image](https://user-images.githubusercontent.com/9260413/103477673-17ce7300-4d8f-11eb-873e-2cda584dfd4e.png)

**Comment by hbenl** [comment]
I had never thought about adding a suite with children, instead I expected an empty suite to be added and the children then added in separate test run events.
Thanks for figuring this out and fixing it!
