### ISSUE TITLE
Add support for Google Tests on CMake

### ISSUE THREAD

**Issue by nico-castell** [hbenl/vscode-test-explorer#188]
# Google Tests

Hello, It would be nice if the test explorer could support **Google Tests** in a **CMake** project.

Maybe process the output of the *ctest* command?

**Comment by hbenl** [comment]
Have you tried the [CMake Test Explorer](https://marketplace.visualstudio.com/items?itemName=fredericbonnet.cmake-test-adapter)?

**Comment by nico-castell** [comment]
Hello, yes I had tried it, without positive results. I finally found [C++ TestMate](https://marketplace.visualstudio.com/items?itemName=matepek.vscode-catch2-test-adapter) and it worked.

Thanks for your help!
