### ISSUE TITLE
Test cases not Loading for Jest

### ISSUE THREAD

**Issue by sachin-agarwal-by** [hbenl/vscode-test-explorer#190]
I am using Vs Code test explorer extension for Jest and found that test cases not loading in explorer.

![image](https://user-images.githubusercontent.com/69183793/109322245-10e84c00-7878-11eb-93a0-e79a14f4bf38.png)

**Comment by hbenl** [comment]
This is caused by the Jest Test Explorer extension, not this one (this one is only providing the UI), so you should open an issue in their repo.
