### ISSUE TITLE
EACCES error while loading tests

### ISSUE THREAD

**Issue by farmergaetano** [hbenl/vscode-test-explorer#2]
For Version 0.2.1.

I'm using the Google Test Explorer version 0.2.0 in Visual Studio Code Version 1.23.1 on MacOS.  When I press the play button for the test, the following warning notification appears on the bottom right.

`Error while loading tests: Error: spawn EACCES`

**Comment by hbenl** [comment]
This sounds like an issue with the Google Test Explorer rather than this extension which only provides the UI. Please file a bug in that extension's [repository](https://github.com/OpenNingia/vscode-google-test-adapter).
