### ISSUE TITLE
Question about `autorun` feature

### ISSUE THREAD

**Issue by matepek** [hbenl/vscode-test-explorer#20]
Calling my adapter's `autorunEmitter.fire()` event will cause two `run([...])` calls.

The second one is definitely a duplicate.

Let me know, if you need more info.

Regards,

**Comment by matepek** [comment]
Okay, I got it

This caused (my code):

> this.testsEmitter.fire({type: 'finished', suite: this.allTests});
>  this.autorunEmitter.fire();

If a file is 'touched' I will try to reload it

> this.testsEmitter.fire({type: 'started'});
> // modifying the affected `TestSuiteInfo` 
> this.testsEmitter.fire( {type: 'finished', suite: this.allTests});

**Important note**: I'm not deleting the suite and its children because then I would  lose the UI states(expand-state, previous results of the children), just adding or removing items.)

I thought on this morning that I should fire `autorun` after this, but the Test Explorer UI feature works without it. 

Can you tell me an example scenario when a adapter should use `autorun`?

What happens if I emit events in order like this:

> this.testsEmitter.fire({type: 'started'});
> this.testsEmitter.fire({type: 'started'});
> this.testsEmitter.fire( {type: 'finished', suite: this.allTests});
> this.testsEmitter.fire( {type: 'finished', suite: this.allTests});

Because now my code can do this: When two test files are being touched.
I suppose it isn't good, and I should prevent it, but it will/would make my code more complex.

**Comment by hbenl** [comment]
Yes, when you reload the tests, the Test Explorer will automatically fire `autorun` afterwards. I will update the documentation to make this clear.

> What happens if I emit events in order like this: [...]

The Test Explorer should handle these events correctly (if you find it doesn't, please file another bug report). And I have to admit that I currently don't prevent this situation from happening in my own adapters either, but I plan to do this eventually.

**Comment by matepek** [comment]
> but I plan to do this eventually.
So it maybe wont be supported in the future? Please let me know about when it happens. Until then I will leave my code like this. (This situation doesn't happen too often anyway.)

Thanks for the support,

**Comment by hbenl** [comment]
> So it maybe wont be supported in the future?

I was only talking about adding code to my own adapters to prevent them from loading the tests twice in parallel. The Test Explorer, however, should always support it if an adapter sends the events as you described. After all, this *is* a rare scenario, so I don't expect all adapters to add code to prevent it.
