### ISSUE TITLE
Test explore does not display logs in output window

### ISSUE THREAD

**Issue by KrupalJoshi** [hbenl/vscode-test-explorer#201]
Extension is not display on going logs in output window for running test cases.

Language: Python
Framework: Pytest

Steps:

1. Run test cases.
2. Open output window.
3. Select 'Test Explorer'.

Expected result: Extension should display logs for running test cases so user can know activity of test case.

**Comment by hbenl** [comment]
You need to click on the test in the test tree to show its logs, otherwise the logs won't be copied to the "Test Explorer" output panel.

**Comment by KrupalJoshi** [comment]
Yes, tried it. Logs are not displaying while tests are running.

It will display once all test cases under the tree are completed

**Comment by WittmannF** [comment]
In my case I had to head to "Output" and then select "Python Test Log":

![Image](https://github.com/user-attachments/assets/09d0e47c-efc3-4524-93ae-02add6bae6d9)
