### ISSUE TITLE
Test Explorer stops working if there is a Risky Test reported

### ISSUE THREAD

**Issue by GavOutdoors** [hbenl/vscode-test-explorer#203]
When PHP Unit throws coverage warnings (i.e. Risky tests), the Test Explorer server fails with this message:

events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/- /Users/Gav/OneDrive/Grayston/NetworkModel/code/src/NetworkModel/ELR.php'
Emitted 'error' event on ReadStream instance at:
    at internal/fs/streams.js:147:14
    at FSReqCallback.oncomplete (fs.js:171:23) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/- /Users/Gav/OneDrive/Grayston/NetworkModel/code/src/NetworkModel/ELR.php'
}
[Info  - 12:05:30 PM] Connection to server got closed. Server will restart.
(node:84567) UnhandledPromiseRejectionWarning: Error: Unhandled method TestRunStartedEvent-e8e2efdeb95cc55423c9a6a88d2dc05b
    at /Users/Gav/.vscode/extensions/recca0120.vscode-phpunit-2.0.76/server/out/server.js:1:9133
    at /Users/Gav/.vscode/extensions/recca0120.vscode-phpunit-2.0.76/server/out/server.js:1:9427
    at Immediate.<anonymous> (/Users/Gav/.vscode/extensions/recca0120.vscode-phpunit-2.0.76/server/out/server.js:1:9788)
    at processImmediate (internal/timers.js:461:21)
(Use `Code Helper (Renderer) --trace-warnings ...` to show where the warning was created)
(node:84567) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:84567) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:84567) UnhandledPromiseRejectionWarning: Error: Unhandled method TestRunStartedEvent-e8e2efdeb95cc55423c9a6a88d2dc05b
    at /Users/Gav/.vscode/extensions/recca0120.vscode-phpunit-2.0.76/server/out/server.js:1:9133
    at /Users/Gav/.vscode/extensions/recca0120.vscode-phpunit-2.0.76/server/out/server.js:1:9427
    at Immediate.<anonymous> (/Users/Gav/.vscode/extensions/recca0120.vscode-phpunit-2.0.76/server/out/server.js:1:9788)
    at processImmediate (internal/timers.js:461:21)
(node:84567) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:84567) UnhandledPromiseRejectionWarning: Error: Unhandled method TestRetryEvent-e8e2efdeb95cc55423c9a6a88d2dc05b
    at /Users/Gav/.vscode/extensions/recca0120.vscode-phpunit-2.0.76/server/out/server.js:1:9133
    at /Users/Gav/.vscode/extensions/recca0120.vscode-phpunit-2.0.76/server/out/server.js:1:9427
    at Immediate.<anonymous> (/Users/Gav/.vscode/extensions/recca0120.vscode-phpunit-2.0.76/server/out/server.js:1:9788)
    at processImmediate (internal/timers.js:461:21)
(node:84567) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:84567) UnhandledPromiseRejectionWarning: Error: Unhandled method TestRetryEvent-e8e2efdeb95cc55423c9a6a88d2dc05b
    at /Users/Gav/.vscode/extensions/recca0120.vscode-phpunit-2.0.76/server/out/server.js:1:9133
    at /Users/Gav/.vscode/extensions/recca0120.vscode-phpunit-2.0.76/server/out/server.js:1:9427
    at Immediate.<anonymous> (/Users/Gav/.vscode/extensions/recca0120.vscode-phpunit-2.0.76/server/out/server.js:1:9788)
    at processImmediate (internal/timers.js:461:21)
(node:84567) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

Here's the PHP Unit Output that isn't being handled.

There were 3 risky tests:

1) EngineeringTrackLocationTest::testTrackDirection
This test executed code that is not listed as code to be covered or used:
- /Users/Gav/OneDrive/Grayston/NetworkModel/code/src/NetworkModel/ELR.php:207
- NetworkModel\ELR::__construct

2) EngineeringTrackLocationTest::testTrackUse
This test executed code that is not listed as code to be covered or used:
- NetworkModel\ELR::__construct

3) EngineeringTrackLocationTest::testTrackId
This test executed code that is not listed as code to be covered or used:
- NetworkModel\ELR::__construct

OK, but incomplete, skipped, or risky tests!
Tests: 3, Assertions: 8, Risky: 3.

**Comment by AlexHaxe** [comment]
it seems like you are using phpunit extension from https://marketplace.visualstudio.com/items?itemName=recca0120.vscode-phpunit so you should open an issue over there: https://github.com/recca0120/vscode-phpunit/issues 

they seem to have an [open issue](https://github.com/recca0120/vscode-phpunit/issues/21) with something that looks similar to your problem, but most of it is in chinese, so I don't know if your case is a new issue or a +1

**Comment by GavOutdoors** [comment]
Ah, thanks! I didn't realise it was PHPUnit causing the problem. 
I've disabled that and all is good :-)
