### ISSUE TITLE
When will vscode v1.52.1 be supported

### ISSUE THREAD

**Issue by JoeEmp** [hbenl/vscode-test-explorer#206]

**Comment by hbenl** [comment]
You can downgrade the extension to version 2.20.1, which still works in VSCode 1.52.1:
Go to the extensions sidebar and click the gear button at the right of this extension's entry, choose "Install Another Version..." and then "2.20.1".

**Comment by alambertt** [comment]
I have VSCode 1.55 version and doesnt show the extension icon on sidebar ☹
