### ISSUE TITLE
Option to disable PHPUnit code completion suggestions

### ISSUE THREAD

**Issue by PH7-Jack** [hbenl/vscode-test-explorer#207]
Disable it
![image](https://user-images.githubusercontent.com/38913462/121022213-86698f80-c778-11eb-8de7-5498365895de.png)

**Comment by hbenl** [comment]
Test Explorer does not display these suggestions, please open an issue in the PHPUnit repo.

**Comment by PH7-Jack** [comment]
If i disable this extension, theses suggestions don't show
If not with that extension, what is the repository?
