### ISSUE TITLE
debug-all and debug-file commands?

### ISSUE THREAD

**Issue by The-Compiler** [hbenl/vscode-test-explorer#211]
Looks like most commands provided by Test Explorer in the command palette have a debug equivalent:

- `rerun` -> `redebug`
- `run-test-at-cursor` -> `debug-test-at-cursor`
- `rerun` -> `redebug`

However, that's not the case for `run-all` and `run-file`, i.e. there's no `debug-all` or `debug-file`. Is there a reason for that?

By the way, thanks for the great extension! :+1: Makes it much easier for Live Share sessions, and also has some other perks I'm missing from the Python extension.

**Comment by hbenl** [comment]
The only reason is that I thought there was no use for it (I usually only run single tests in the debugger). But since you're asking I guess you have a use for it, so I'll add this soon.

**Comment by The-Compiler** [comment]
FWIW the main reason is that I'm building a [VSpaceCode](https://vspacecode.github.io/) menu for test explorer:

![image](https://user-images.githubusercontent.com/625793/121817653-f305f200-cc82-11eb-860b-9f67b0c19596.png)

and it just seemed off to have upper-case equivalents for most except those two :slightly_smiling_face:.

But I'd probably use at least `debug-file` from time to time indeed, when e.g. working on a new feature and having multiple tests with breakpoints in them.

**Comment by hbenl** [comment]
I have added the debug-file and debug-all commands now.
