### ISSUE TITLE
Can't find Node.js binary

### ISSUE THREAD

**Issue by AnthonMS** [hbenl/vscode-test-explorer#220]
I am just starting up with testing react apps and I am having some troubles with this extension.

When I manually run the tests with the command `npm test` it works fine. At the moment of writing this, I have 36 passed tests and 3 failed tests.

I then started looking into an extension to run the tests for me, since it would be nice having a button in vs code to tell me exactly where the test failed and a button to open the source for the failed tests. And I found this extension, which seemed promising.

The extension finds my tests successfully, but when I run them, all of them fails, which I find weird. I then try to click on the debug this test button and it gives me this error.
![Skærmbillede 2021-07-27 134936](https://user-images.githubusercontent.com/23500433/127149257-05f00f34-8ca9-4454-9173-9efb17fe1025.png)

I have tried google, but haven't been able to find the magic solution to solve all my problems, so I was hoping maybe someone could help me figure out why this is happening. I have added a configuration in the launch.json so it looks like this:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Run Tests",
            "cwd": "/home/ams/projects/valinor-frontend/",
            "runtimeExecutable": "npm",
            "runtimeArgs": [
                "test"
            ]
        }
    ]
}
```

I have also tried some other config setups, but none of them have worked. 

I hope someone here is able to tell me where I'm going wrong.

Edit: I am developing on WSL 2 Ubuntu 20.04 and all my other extensions work fine and it seems the launch config above is also able to work if I run it from the VSCode Debug tab (Though nothing is outputtet in the Debug console since I think I am doing something wrong there as well).

Thanks in advance.

**Comment by AlexHaxe** [comment]
it might be worth opening an issue over here https://github.com/smarschollek/vscode-react-scripts-test-adapter (if that is the test adapter you are using)

**Comment by AnthonMS** [comment]
You're right, that might be a good idea as well. I just couldn't find the repo for this extension since clicking on repository on [here](https://marketplace.visualstudio.com/items?itemName=smarschollek.vscode-react-scripts-test-adapter&ssr=false#overview) gave a 404 error. So thought this was the main repo for issues regarding any of those extensions.

But thanks, I will give it a try.

**Comment by hbenl** [comment]
Fixed in  smarschollek/vscode-react-scripts-test-adapter#1
