### ISSUE TITLE
Java unit tests using Test Explorer UI

### ISSUE THREAD

**Issue by MartinBalin** [hbenl/vscode-test-explorer#224]
Hello,
I just wanted to point out that the list of https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer supported languages is missing Java. Apache NetBeans Language Server https://marketplace.visualstudio.com/items?itemName=ASF.apache-netbeans-java provides Java unit tests support using Test Explorer UI. I believe this will be a good addition to your list of where Test Explorer UI is used.
Anyway great work you do we could built on.

**Comment by hbenl** [comment]
Thanks, I've added it to the README.
