### ISSUE TITLE
Only running first test

### ISSUE THREAD

**Issue by tyler36** [hbenl/vscode-test-explorer#225]
I've been using TestExplorer with PHPUnit TestExplorer for quite a while and recently started using the "useNativeTesting" option.

As of `1.59.0` however, TestExplorer with only run the first test when I click the "Run all tests" button. I can run all tests in a file or an individual test by click on the button in the test tree. If I disable "useNativeTesting", I can run all tests.

I tried a portable VScode `1.58` and it worked. That's using a different version of TestAdapter and TestExplorer. Upgrading the install to `1.59` also updates the extentions.

It fails on the current VScode Insider `1.60` (2021-08-18) too. 

OS: Win10
Vscode: `1.59.0`
TestExplorer: `2.21.0`
PHPUnit TestExplorer: `2.0.76`
Test Adapter Converter: `0.1.2`

**Comment by hbenl** [comment]
Other test adapters don't seem to have this problem, so you should report this issue in the repo for PHPUnit TestExplorer.
