### ISSUE TITLE
How to check whether autorun is activated or deactivated?

### ISSUE THREAD

**Issue by alexanderadam** [hbenl/vscode-test-explorer#228]
It seems that tests are always running in my case (maybe the same issue as [this](https://github.com/connorshea/vscode-ruby-test-adapter/issues/52) or [this](https://github.com/Derivitec/vscode-dotnet-adapter/issues/49) [or is it rather related to [this](https://github.com/microsoft/vscode/issues/54308)?]) and I want to disable autorun for a heavy project.

But currently I have the feeling that this menu entry isn't working at all, since VSCode somehow always spawns test runners in the background.

So is there any possibility to check whether disabling worked?

**Comment by hbenl** [comment]
If autorun is enabled, the icons in the tree view show a little play icon. In this screenshot, autorun is enabled for the "Sourcemapped tests" but not "Typescript tests": 
![Screenshot_2021-11-06_18-52-16](https://user-images.githubusercontent.com/16060807/140619094-fc090aec-928f-4224-87b2-785d8ec08c9d.png)
What is being spawned in the background are runners for updating the test definitions in Test Explorer's tree view.

**Comment by ryanhageman** [comment]
I'm having the same problem

**Comment by hbenl** [comment]
@ryanhageman If you're talking about the extension automatically starting child processes for updating the test definitions, you can turn that of by setting `mochaExplorer.autoload` to `false` in your VS Code settings.

**Comment by hbenl** [comment]
@ryanhageman You should file an issue in the repository for the test adapter that you are using.
