### ISSUE TITLE
Test autorun not available when using useNativeTesting in python

### ISSUE THREAD

**Issue by simgunz** [hbenl/vscode-test-explorer#231]
Considering python, from what I understand by setting `"testExplorer.useNativeTesting": true` the extension still uses the python test adapter `Python Test Explorer for Visual Studio Code` but it uses the native vscode UI instead of the old one to expose it to the user.

Though, when I enable this option I am no longer able to use the feature test autorun of `Python Test Explorer for Visual Studio Code
`, because it is not exposed in the native UI (which [supports it](https://github.com/microsoft/vscode/commit/e21134dd71ebf8db7ea092eac94413584bdecf54)).

**Comment by hbenl** [comment]
Are you sure that native testing already supports autorun? I couldn't find anything in the UI for enabling it (I looked at Microsoft's [test provider sample](https://github.com/microsoft/vscode-extension-samples/tree/main/test-provider-sample)). If it does then this issue should be moved to the [converter extension](https://github.com/microsoft/vscode-test-adapter-converter) that is used when `testExplorer.useNativeTesting` is `true` to translate between the Test Explorer API and the native testing API.
