### ISSUE TITLE
I have no color in my output tab

### ISSUE THREAD

**Issue by surezluvy** [hbenl/vscode-test-explorer#238]
![image](https://user-images.githubusercontent.com/70625779/172298592-179b12c1-778f-46b5-abb0-3a79e9ed849b.png)
I have no color in my output tab

**Comment by hbenl** [comment]
The "PHPUnit Language Server" output channel is not from this extension but from the "PHPUnit Test Explorer" extension (I guess), so this issue should be filed there.
