### ISSUE TITLE
Native Testing does not work (Ruby)

### ISSUE THREAD

**Issue by finnove** [hbenl/vscode-test-explorer#239]
I tried to turn on testExplorer.useNativeTesting = true, but this does not work.
GUI shows the progress x of 170 tests passed...suddenly changing to 16/16 tests passed and stops.
However - when I monitor the Ruby Test Explorer logfile, the tests are indeed running in the background... but the GUI does not update.
When I click a single tests, they seem to work, but when I try to run multiple, it fails.
Also when trying only system tests its says x of 40 tests passed..suddenly changing to 20/20 passed.
The logfile seem to indicate that the tests pass.
So logfile and test process seems right. GUI seems lost.
Everything works fine when Native Testing = false

**Comment by hbenl** [comment]
Please open this issue in https://github.com/microsoft/vscode-test-adapter-converter.
