### ISSUE TITLE
extremely slow debugger if breakpoint is present

### ISSUE THREAD

**Issue by BjorHart** [hbenl/vscode-test-explorer#240]
I am writing pytests for a module and want to debug my way through the tests. To debug my debugger issue i created a simple test:
```
def test_something():
    pass
```
which takes 0.001 seconds to run in the terminal. If i try to debug this test WITH A BREAKPOINT, using vscodes test explorer UI extension(Holger Benl) the same test takes 40-80 seconds to complete. If there is NO BREAKPOINT, the test runs in 4 seconds with the debugger (hitting debug).

I cant figure out why this is. The time increase of the terminal to debug run without breakpoint is also huge, but some delay due to vscode running debug is exoected I guess.

Any suggestions?

**Comment by hbenl** [comment]
No idea, but I don't think it's caused by this extension. It's most probably an issue with the extension that you use for debugging python or with the pytest extension (which is responsible for configuring the python debugger when you debug tests).
