### ISSUE TITLE
Crashes but won't produce a dump

### ISSUE THREAD

**Issue by boatcoder** [hbenl/vscode-test-explorer#241]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Type: <b>Bug</b>

Debug a test
Restart the Debug Run

Message is: The window has crashed (reason: 'clean-exit', code: 1)

There are buttons for close and reopen and neither of them work.

Force Quit is required which is a PITA.

Extension version: 2.21.1
VS Code version: Code 1.70.0 (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:39:20.716Z)
OS version: Darwin arm64 21.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.24GB free)|
|Process Argv|--disable-extensions --crash-reporter-directory /tmp .|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30529769
vsclangdc:30486549
c4g48928:30535728
hb751961:30543456
dsvsc012:30540252

```

</details>

**Comment by boatcoder** [comment]
I'm testing Django code that is being run under pytest.

**Comment by hbenl** [comment]
This is not related to this extension (which only provides the UI for testing), you should open an issue in the repository for the pytest adapter.
