### ISSUE TITLE
Sort Test Suites

### ISSUE THREAD

**Issue by cah-dgreif** [hbenl/vscode-test-explorer#26]
It would be nice to be able to sort the test suites alphabetically.  If you have a lot of test suites in multiple folders, it's hard to find the one you are looking for in the explorer without going to the file and clicking the "Show in Test Explorer" button.

**Comment by hbenl** [comment]
Version 2.6.0 of the Test Explorer allows you to sort tests and suites by label or location (using the `testExplorer.sort` configuration property).
