### ISSUE TITLE
[Question] Is lazy-load supported?

### ISSUE THREAD

**Issue by jdneo** [hbenl/vscode-test-explorer#30]
From my understanding, currently, the test adapter needs to search for all the test items and return them to the UI in one call.

Is it possible to support lazy-load for the explorer? For example, each time the user clicks on a tree node, the Explorer UI will call the adapter to return the direct children for that node?

**Comment by hbenl** [comment]
No, this isn't supported and I'm not planning to add support for it, sorry.
