### ISSUE TITLE
Need PHP support

### ISSUE THREAD

**Issue by tiansin** [hbenl/vscode-test-explorer#31]
Thank you very much.

**Comment by calebcartwright** [comment]
I think I've got an idea of how to implement this, at least for [PHPUnit](https://phpunit.de/).

It will probably be a little while before I can get started on this, but will try to get around to it at some point

**Comment by calebcartwright** [comment]
Looks like someone else has already taken care of this! Refs #68 

https://marketplace.visualstudio.com/items?itemName=recca0120.vscode-phpunit
