### ISSUE TITLE
improve path handling for gutter and codelens

### ISSUE THREAD

**Issue by AlexHaxe** [hbenl/vscode-test-explorer#35]
https://github.com/hbenl/vscode-test-explorer/blob/a91fba04af4f840f0f72ea3e9846ea03219c5c57/src/decorator.ts#L40

when writing a test adapter for Haxe I ran into an issue that would only show on Windows. Gutter and codelens would not show any info, however "Show source" in tree would jump to the correct location.
After debugging what went wrong I found out my paths had `/` instead of `\` and so they wouldn't match.
Windows accepts both variants, so they should probably also work here.

**Comment by hbenl** [comment]
Starting with version 2.4.1 Test Explorer will [normalize](https://github.com/hbenl/vscode-test-explorer/blob/2122186b978ca8b570eb14274642dbb4214421ef/src/util.ts#L202) all filenames using the `vscode.Uri` class. This should ensure that they match the filenames from VS Code - at least it will catch the 2 most common inconsistencies with Windows paths: `/` vs. `\` and `C:\` vs. `c:\`.
