### ISSUE TITLE
Make debug optional

### ISSUE THREAD

**Issue by KamasamaK** [hbenl/vscode-test-explorer#37]
I am working on an adapter for a language that does not have a debugger. It would be nice if I could declare that it does not support debugging so that those options are hidden.

**Comment by hbenl** [comment]
I've made the `debug()` method optional in version 1.3.0 of the vscode-test-adapter-api package. Test Explorer version 2.5.0 will only show menu items and code lenses for debugging if the `debug()` method is defined.
Thanks for the suggestion!

**Comment by KamasamaK** [comment]
That was fast. Thanks a lot!
