### ISSUE TITLE
Feature Request: Command to reveal test-view

### ISSUE THREAD

**Issue by HaaLeo** [hbenl/vscode-test-explorer#38]
# Description
It would be awesome if the extension could contribute a command that simply focuses the test view and bind it by default to <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>T</kbd> (Like <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>E</kbd> for the explorer view)

# Use case
As a developer I want to be able to show/hide the test view via a keybinding to speed up my workflow.

**Comment by jonyeezs** [comment]
Isn't that this?:

```json
{
  "key": "ctrl+shift+t",
  "command": "test-explorer.focus"
}
```

**Comment by HaaLeo** [comment]
thanks, perfect. Missed this one.
