### ISSUE TITLE
Search tests

### ISSUE THREAD

**Issue by sourcier** [hbenl/vscode-test-explorer#4]
As a user
When there is a large number of tests
I would like to be able to filter the list of tests in the side
So that I can find a test I want to run/debug quickly

**Comment by hbenl** [comment]
Let's hope that Microsoft/vscode#50062 gets implemented soon...

**Comment by connorshea** [comment]
The custom tree views has a PR open now, hopefully this’ll come with the July release! 🙏

**Comment by connorshea** [comment]
I think this should be fixed with today's release of VS Code?

**Comment by connorshea** [comment]
<img width="482" alt="Screen Shot 2019-08-08 at 8 54 51 PM" src="https://user-images.githubusercontent.com/2977353/62750868-ccd7f100-ba1e-11e9-9f84-d87bdfbdd403.png">
Yup, you can just click into the test explorer view and start typing, and it'll highlight matches. You can hover over the search box and switch to filter mode, where it'll only show matching tests/groups.

**Comment by hbenl** [comment]
Hooray for VS Code's new tree widget :)
