### ISSUE TITLE
Run individual tests from explorer

### ISSUE THREAD

**Issue by avahe-kellenberger** [hbenl/vscode-test-explorer#42]
# Issue
Currently, clicking to run an individual test (as opposed to all tests) does nothing.

# Expectation/Suggestion
Clicking the `run` icon next to an individual test or file will run the respective test(s).

## Current setup:
Using Jest on Linux - all tests are found, but are not ran when clicked individually.

# EDIT:
By viewing the `Jest Test Explorer Log` I've found that the search query is incorrect:
`test/unit/entity/Entity\\\\.spec\\\\.ts•^setLocation moves the object only when given location is different$`

The correct folder is being searched, but the four backslashes on either side are incorrect, and I can not find supporting documentation on this issue.

`jest.config.js`:

```javascript
module.exports = {
    // An array of file extensions your modules use
    moduleFileExtensions: ['js', 'ts', 'tsx'],

    // A list of paths to directories that Jest should use to search for files in
    roots: ['<rootDir>/test'],

    // The regexp pattern or array of patterns that Jest uses to detect test files
    testRegex: ['/__tests__/.*\\.(ts|tsx|js)$'],

    // A map from regular expressions to paths to transformers
    transform: {
        '\\.(ts|tsx)$': '<rootDir>/node_modules/ts-jest/preprocessor.js'
    }
};
```

If something is missing or incorrect on my end, please let me know. I've tried several configurations and nothing seems to get rid of the invalid path generated by trying to run single tests.

**Comment by hbenl** [comment]
This is an issue in the [Jest adapter](https://github.com/rtbenfield/vscode-jest-test-adapter) - please file this issue in that repository.
