### ISSUE TITLE
Switch to the Test activity automatically when a run test command is invoked

### ISSUE THREAD

**Issue by xen22** [hbenl/vscode-test-explorer#43]
It would be useful to show the test tree when tests are started to avoid having to switch to the Test activity  manually. Almost every time I need to run tests (either via a hot-key assigned to the "Run all tests" command or via the hyperlink in the code), I like to see how the test run is progressing by looking at the test tree.

BTW, it looks like vscode API supports this via the reveal method on the view:

![image](https://user-images.githubusercontent.com/18519338/53847900-52421a00-4017-11e9-98fa-57024b62f9b0.png)

**Comment by hbenl** [comment]
I have added the `testExplorer.showOnRun` configuration property to version 2.7.0.

**Comment by xen22** [comment]
Thanks, works well!
