### ISSUE TITLE
Button on test tree to expand/collapse all test suites

### ISSUE THREAD

**Issue by xen22** [hbenl/vscode-test-explorer#44]
Useful to quickly get a view of actual tests inside the test suites

**Comment by hbenl** [comment]
I have added the `testExplorer.showCollapseButton` and `testExplorer.showExpandButton` configuration properties to version 2.7.0. `testExplorer.showExpandButton` is a number specifying the number of levels that should be expanded (the maximum is 3).

**Comment by Gama11** [comment]
Nice! I'm a bit concerned about discoverability with the settings being off by default, but oh well.

Anyway, why I'm actually commenting: both buttons seem to have some performance issues with a large amount of tests / suites. In my case, the UI hangs for several seconds after clicking one of the buttons.

I'm not sure how you've implemented it (seems the commits for 2.7.0 haven't been pushed yet?), but at least for `collapseAll`, using VSCode's built-in `showCollapseAll` option might be an option, if you're not doing that already:

https://code.visualstudio.com/api/references/vscode-api#TreeViewOptions

**Comment by Simn** [comment]
It would be better to show these buttons by default.

**Comment by hbenl** [comment]
I'm already using VS Code's built-in collapse button, for this and for expanding there aren't any alternative ways to achieve this anyway (at least AFAIK).
The VS Code developers are gradually introducing a new tree widget to fix the performance problems of the current one, let's hope they offer it to extensions soon.
P.S. I pushed the commits now.

**Comment by xen22** [comment]
Thanks for implementing this.
I would also recommend showing them by default but perhaps it's worth waiting until the performance issues are resolved by the VSCode team.

**Comment by connorshea** [comment]
I would also appreciate this as a default, I didn't know the feature existed until I looked for an issue about collapsing them.

**Comment by hbenl** [comment]
I enabled them by default in version 2.10.0.

**Comment by connorshea** [comment]
\o/ thanks!
