### ISSUE TITLE
Show test statistics in the VSCode status bar

### ISSUE THREAD

**Issue by xen22** [hbenl/vscode-test-explorer#45]
It would be useful if TestExplorerUI showed statistics in the status bar such as:
- total number of tests discovered (once discovery has completed)
- number of tests passed, failed, ignored/not run

Here's an example from the .Net Test Explorer extension:
![image](https://user-images.githubusercontent.com/18519338/53978789-f25f8680-4170-11e9-8b5f-3f67a49f691d.png)

**Comment by xen22** [comment]
Some more examples:
![statusbar4](https://user-images.githubusercontent.com/18519338/53979679-584d0d80-4173-11e9-84bb-77c08b4da0c8.png)
![statusbar3](https://user-images.githubusercontent.com/18519338/53979680-584d0d80-4173-11e9-8756-2d02074edb83.png)
![statusbar2](https://user-images.githubusercontent.com/18519338/53979681-58e5a400-4173-11e9-8a80-ecdbf8ae1203.png)

**Comment by hbenl** [comment]
Actually I was hoping that someone else would write a separate extension for this - the [Test Controller Example](https://github.com/hbenl/vscode-example-test-controller) already contains a (very incomplete) implementation.

**Comment by connorshea** [comment]
I'd like this as an official feature as well, though I understand if you think it should be separate.

**Comment by connorshea** [comment]
I've created an extension for this :)

![Screen-Recording-2019-06-08-at-3 28 08-PM](https://user-images.githubusercontent.com/2977353/59152497-590b6f00-8a02-11e9-8fe4-d315a99e7cc2.gif)

The converter made the gif slower than the original screen recording and decreased the framerate, and there's a bit of dead time while RSpec starts up, but other than that it's pretty representative of real use :)

**Comment by connorshea** [comment]
And here it is: https://marketplace.visualstudio.com/items?itemName=connorshea.vscode-test-explorer-status-bar

**Comment by hbenl** [comment]
Thanks!

**Comment by xen22** [comment]
That is excellent, thanks!
