### ISSUE TITLE
Cancelling test run does not clear state of running suites/tests

### ISSUE THREAD

**Issue by xen22** [hbenl/vscode-test-explorer#47]
If a test run locks up (or takes too long) and I cancel it by pressing the red stop button, my adapter will emit a TestRunFinishedEvent event (<TestRunFinishedEvent>{ type: 'finished' }) to ensure the red button reverts to the 'play' icon. The problem is that the icons for the test suites that were still in progress do not change. It would be good if TestExplorer updated the states of these suites -  perhaps to an "Errored" state?

Test suites before stopping the run:
![image](https://user-images.githubusercontent.com/18519338/54259481-bdb55a00-45ca-11e9-882f-2182071cf9e0.png)

and after stopping the run:
![image](https://user-images.githubusercontent.com/18519338/54260037-a11a2180-45cc-11e9-8956-e4240ced6d93.png)

Note: in case it's relevant, when I run the tests, the adapter does not send TestSuiteEvents (either 'running' or 'completed') only TestEvents ('running', 'passed'/'failed'/etc.) The behaviour is as expected without the test suite events, except when stopping the test run.

**Comment by hbenl** [comment]
The Test Explorer should already do this, I don't know why it isn't working in your case.
If you give me an example project to reproduce this, I will have a look why this is happening.

**Comment by xen22** [comment]
This issue was caused by my adapter - when sending tests to TestExplorer the adapter was not setting the id of the root node. Once I set a unique id for the root node (and sent that to TestExplorer when running all tests), it worked fine. 
Closing the issue.
