### ISSUE TITLE
Show stack trace in TestExplorer output for failed tests

### ISSUE THREAD

**Issue by xen22** [hbenl/vscode-test-explorer#48]
When clicking on a test, "Test Explorer" output for this test will show the output of the failed asserts:

![image](https://user-images.githubusercontent.com/18519338/54303863-cf2d4f00-4628-11e9-8bda-5c212eb680ba.png)

It would be really nice if it would also show the call stack where the error occurred. The adapter returns the call stack in the decorations field of TestEvent.

**Comment by hbenl** [comment]
It is up to the Test Adapter to append the call stack to the message for the failed test.
