### ISSUE TITLE
Click to view code for test

### ISSUE THREAD

**Issue by sourcier** [hbenl/vscode-test-explorer#5]
As a user,
I would like to be able to view the code for the test I have clicked on the side bar, in the editor area
So that I can better understand what the test is doing.

**Comment by hbenl** [comment]
Try the "Show source" context menu item for tests, I think that is what you're looking for.

**Comment by sourcier** [comment]
The context menu is cool, but it will be very tedious to do it every time, would it be possible to make it do the same on on click/double click instead? Maybe put the feature behind a config option?

**Comment by hbenl** [comment]
Yes, I will make this configurable (eventually).

**Comment by flovilmart** [comment]
<img width="561" alt="capture d ecran le 2018-07-03 a 20 19 11" src="https://user-images.githubusercontent.com/364568/42250378-7d9aabc0-7efe-11e8-909b-041a95a7e365.png">


@hbenl what do you think of this solution? Double Click seem hard to do, perhaps with a nice icon and we'd be set?

**Comment by sourcier** [comment]
That works pretty well, vscode has a good icon for this in the file view:

<img width="75" alt="screen shot 2018-07-04 at 09 56 38" src="https://user-images.githubusercontent.com/16674724/42267446-f10d8e52-7f70-11e8-8468-7c7d06a78421.png">

A shortcut for the command could also be useful.

**Comment by flovilmart** [comment]
@sourcier i’M not sure I can reuse icons from vS-code but i’ll try.

**Comment by sourcier** [comment]
A similar icon would suffice if we can't reuse the built in one, I just thought the icon was very clear in what it does.

**Comment by flovilmart** [comment]
@sourcier indeed :) but as lazy as I am, looking for a dark + light icon versus using an existing one + learning a new trick :)

**Comment by hbenl** [comment]
@flovilmart Thanks for the PR, I just published it.
