### ISSUE TITLE
Need a configuration to enable auto run by default

### ISSUE THREAD

**Issue by AnakinMac** [hbenl/vscode-test-explorer#51]
It is annoying that users need to click enable auto run every time they open VSCode workspace. It will be nice if there is a configuration to make auto run the default.

**Comment by matepek** [comment]
I guess the identification is the hard part of it.

If you don't mind, I would like to share my thoughts about it.

Root could be:
```js
{}
```

suite1 only:
```js
{
  "matepek.vscode-catch2-test-adapter": {
    "workspace directory" : {
      "suite1 label": true
    }
  }
}
```

suite1->test1 and suite1->test2 only:
```js
{
  "matepek.vscode-catch2-test-adapter": {
    "workspace directory" : {
      "suite1 label": {
        "test1": true, 
        "test2": true, 
        "test3": false
      }
    }
  }
}
```

With the false and true value it is easy to switch on and off a leaf.
More than one adapter can be set in this structure.

Bests,

**Comment by hbenl** [comment]
In version 2.12.0, Test Explorer remembers the autorun state when VS Code is restarted.
It's not the same thing as putting it in the settings, but it was easier to implement and is easier to use
and I think it covers your use case. Do you agree?

**Comment by matepek** [comment]
I guess, you are asking @AnakinMac.
(From me: good enough.)

**Comment by DaveSanders** [comment]
@hbenl Does this feature still work?  For me, on the latest version (2.21.1) that the autorun setting doesn't "stick" between vscode restarts.

**Comment by hbenl** [comment]
@DaveSanders Yes, this should still work (and does for me). What testing framework are you using?
