### ISSUE TITLE
Sending retire event for 3 tests opens the picker

### ISSUE THREAD

**Issue by matepek** [hbenl/vscode-test-explorer#56]
I think it should not.
<img width="393" alt="Screenshot 2019-04-01 at 15 58 30" src="https://user-images.githubusercontent.com/16504598/55333169-03ad6180-5497-11e9-9e5e-6d2cb0e9bcab.png">

**Comment by hbenl** [comment]
> I think it should not.

It definitely shouldn't!
This is fixed in version 2.9.1.
