### ISSUE TITLE
Ruby support

### ISSUE THREAD

**Issue by connorshea** [hbenl/vscode-test-explorer#57]
Specifically [Rspec](http://rspec.info/), though [Minitest](https://github.com/seattlerb/minitest) is also a fairly popular testing framework for Ruby.

There are some existing extensions that are somewhat similar, but they don't have a UI to display the tests:
- Ruby Test Launcher: https://marketplace.visualstudio.com/items?itemName=blakeh.ruby-test-launcher
- Rails Test Runner: https://marketplace.visualstudio.com/items?itemName=davidpallinder.rails-test-runner

**Comment by connorshea** [comment]
I've created a Ruby test adapter that runs Rspec tests.

![image](https://user-images.githubusercontent.com/2977353/56844242-5269d380-686a-11e9-9839-629b79f576a3.png)

It's currently incredibly slow (a test suite that takes ~7.5 seconds just running `bundle exec rspec` takes 3 minutes when run via the extension) because the tests are run one at a time, and rspec takes a long time to boot, so I need to fix that before I actually release it. But it works! :D

**Comment by connorshea** [comment]
I've released the extension, it should run pretty fast when running the whole test suite: https://marketplace.visualstudio.com/items?itemName=connorshea.vscode-ruby-test-adapter

**Comment by hbenl** [comment]
Awesome!
