### ISSUE TITLE
Test Explorer pane in sidebar remains after Test Explorer UI extension uninstalled

### ISSUE THREAD

**Issue by marvingreenberg** [hbenl/vscode-test-explorer#58]
![testexplorerpane](https://user-images.githubusercontent.com/216707/55574971-c1c12d00-56db-11e9-9c77-37cf95e4be73.png)

But the "Test Explorer UI" (and Python Test Explorer) have been uninstalled, and vscode restarted.

![uninstalled](https://user-images.githubusercontent.com/216707/55575027-e61d0980-56db-11e9-9a21-adfa50379661.png)

Strangely, reinstallling gives an even stranger result...

![reinstall](https://user-images.githubusercontent.com/216707/55575173-4744dd00-56dc-11e9-8760-b0cde4bd9902.png)

**Comment by hbenl** [comment]
The 2 views that can be seen in your first screenshot are not from this extension - they don't use the state icons that this extension uses (note that the Test side bar is used by many testing extensions).
In your last screenshot the view in the middle is from this extension.

**Comment by marvingreenberg** [comment]
Sure enough, it's from the Microsoft Java Test Runner.  Sorry.
