### ISSUE TITLE
Error: spawn ENAMETOOLONG

### ISSUE THREAD

**Issue by ekulabuhov** [hbenl/vscode-test-explorer#62]
Hi! All I'm getting in the Output window for Test Explorer channel is this error. And it says "Error while loading test - click to show" in the Extension window. Any way to debug this?

**Comment by hbenl** [comment]
The error message is about an error occurring in the test adapter that you are using, so you'll have to file this issue there. My guess is that the adapter tries to start a child process with a very long argument list (I had the same issue with the mocha adapter when there were many tests in the project).
