### ISSUE TITLE
'Sort by' button in Test Explorer sidebar

### ISSUE THREAD

**Issue by connorshea** [hbenl/vscode-test-explorer#66]
It'd be nice to have a 'Sort by' button in the test explorer UI. Instead of needing to change the sorting method in the Settings, I'd like to be able to change it with a dropdown in the sidebar. Is this possible?

**Comment by hbenl** [comment]
I've added menu items to the main menu in the sidebar in version 2.11.0.

**Comment by connorshea** [comment]
Thanks!
