### ISSUE TITLE
Run test commands from right-click menu

### ISSUE THREAD

**Issue by connorshea** [hbenl/vscode-test-explorer#67]
I'd like to have an option in the right-click menu to run the test at the position I've right-clicked, or run the current file's tests when inside a test file.

For example, I'd expect two menu options here:

<img width="756" alt="Screen Shot 2019-05-09 at 5 52 04 PM" src="https://user-images.githubusercontent.com/2977353/57493667-2e06f180-7283-11e9-8233-217099771154.png">

I know it's possible using the CodeLens or the Command Palette, but I disabled the lens since it caused test files to become pretty cluttered, and the Command Palette is a bit inconvenient. It'd be nice to still have the functionality easily exposed. Maybe make it the right-click menu options an opt-in feature?

**Comment by hbenl** [comment]
I've added the context menu items in version 2.11.0. Since I can't tell VS Code to show them only in test files (at least I don't know how) and didn't want to clutter the context menu, you have to explicitly enable them with the configuration property `testExplorer.addToEditorContextMenu`.
