### ISSUE TITLE
Navigate to test case code

### ISSUE THREAD

**Issue by maziac** [hbenl/vscode-test-explorer#69]
Hi, I‘m developing a test adapter for z80 assembler.
So far its working fine but I was wondering if ther eis an interface to navigate directly to the source code of the test case.
E.g. double clicking the test case in the test explorer could take you directly to the sources of the test case.
Is something similar available or could I do a feature request.

**Comment by hbenl** [comment]
Yes, this is already possible. All you have to do is set the `file` and `line` properties in `TestInfo`/`TestSuiteInfo` (see https://github.com/hbenl/vscode-test-adapter-api/blob/5014a25bd0a6f5b383ca7f4da26559f6f9ecd34d/src/index.ts#L223). The Test Explorer will show an icon next to the test or suite for opening its source:
![Screenshot_2019-05-17_18-35-01](https://user-images.githubusercontent.com/16060807/57943083-70f44500-78d3-11e9-95cf-83746bd8fb81.png)

**Comment by maziac** [comment]
Thanks.
