### ISSUE TITLE
Icon in source file (gutter) not updated

### ISSUE THREAD

**Issue by maziac** [hbenl/vscode-test-explorer#71]
I managed to get the navigation to the test cases working but found a small issue with the icon displayed in the test case file.
If a testcase is executed it is not updated right away. 
Though the icon shows correctly if another location is shown and afterwards the original location is selected again.
Please see the attached animated gif, it should be more clear.
![icon](https://user-images.githubusercontent.com/3081973/57970651-27affe00-7984-11e9-84f9-1d937261c546.gif)

**Comment by hbenl** [comment]
This should be fixed in version 2.11.0.
Please test this and tell me if it works for you.

**Comment by maziac** [comment]
Yes, works now. Thanks.

**Comment by artoale** [comment]
I seem to be having the same issue creep up again, is this possibly a regression?

**Comment by hbenl** [comment]
@artoale could you please provide more details: does it always happen or sporadically? is it reproducible? can you provide a test project with which I can reproduce this?
