### ISSUE TITLE
CTest support

### ISSUE THREAD

**Issue by Clovel** [hbenl/vscode-test-explorer#72]
Hi ! 
I do not know if this is possible, but I was thinking about CTest support for this extension. Has this already been discussed ? Is it feasable ? What would this feature need for it to be implementable ?

**Comment by hbenl** [comment]
I'm sure this is possible, if someone writes an [adapter](https://github.com/hbenl/vscode-example-test-adapter) for it. I haven't seen anyone discussing this so far though.

**Comment by MathiasMagnus** [comment]
I recently came across this extension and indeed, a decent Test Explorer for CTest would be a welcome addition.

**Comment by fredericbonnet** [comment]
Hey! As a matter of fact I've just published a CMake adapter for Test Explorer UI, available here:

https://marketplace.visualstudio.com/items?itemName=fredericbonnet.cmake-test-adapter

I was about to open a new issue about it when I noticed this one.

**Comment by MathiasMagnus** [comment]
Wow! You beat me to it! Awesome. Off to file my first issue. :) Or I'll go ahead and debug the extension myself, see which one of us fixes the issue first.

**Comment by hbenl** [comment]
@fredericbonnet Thanks, I've added a link to the README.
