### ISSUE TITLE
Unable to run test suite due to extension getting stuck in bad state

### ISSUE THREAD

**Issue by connorshea** [hbenl/vscode-test-explorer#75]
Occasionally my Ruby Test Explorer gets into a state where the test suite never finishes running, which makes it impossible for the tests to be re-run (you can still run them per-test or per-suite, of course, but not the whole thing).

<img width="308" alt="Screen Shot 2019-06-02 at 10 09 56 PM" src="https://user-images.githubusercontent.com/2977353/58775532-2c2f0600-8583-11e9-9efc-85363af9c295.png">

I realize this is a bug in my Ruby adapter (or at least, I'm pretty sure it is). However, I think it shouldn't really be a case that the extension can even get into - or at least one that should be recoverable by the end user. I'm not sure exactly what the solution here should be, but I wanted to the problem up. Would it be possible to consider the test suite 'finished' when the test states are reset? Or to provide a separate button in the dropdown to allow any test runs that haven't been finished to become finished?

**Comment by connorshea** [comment]
I'm somewhat suspicious of these lines:

https://github.com/hbenl/vscode-test-explorer/blob/76d8889290d5ceed1d63f30ea1caba4a5e345415/src/testExplorer.ts#L300-L304

If the running count gets messed up in any way, then `testsRunning` won't be able to be set to false, I think?

**Comment by hbenl** [comment]
Yeah, the `runningCount` mechanism is more fragile than it needs to be, I'll replace it with a flag (per adapter), that should be more robust. I also like the idea of considering the test run finished when the user resets the test states - it's the most intuitive place I can think of to put this workaround.
Hint: I usually listen to the child process' `exit` event and send the `TestRunFinishedEvent` there (and _only_ there), that turned out to be very robust (at least for me).

**Comment by connorshea** [comment]
I actually already have it set to finish when the child process `exit` event happens :) I had it sending the event in a few other places as well, which I've now removed. It looks like that has mostly fixed the problem :D

I look forward to the more robust runningCount solution regardless, it'd make the extension much easier to develop adapters for :)

**Comment by hbenl** [comment]
I just published 2.12.0, which contains the improved implementation for determining if any adapters are loading or running tests.
