### ISSUE TITLE
FR: Refresh output channel/window when the last shown test's output changes

### ISSUE THREAD

**Issue by matepek** [hbenl/vscode-test-explorer#76]
- Click on a test -> the output window is opened and the result of the test is shown.
- Enable autorun
- Trigger the test to be run (touch)
=> Still shows the previous run's result.

It would be nice if the output window would be updated.
(Showing the last test)

Please :)

**Comment by matepek** [comment]
Like [this](https://github.com/matepek/vscode-test-explorer/commit/c91e1f919655c6d4e17cc5a9f75dc5381787a543)..

**Comment by hbenl** [comment]
Thanks! I just published 2.12.0 containing this feature.
