### ISSUE TITLE
Find bar vertical padding not adding

### ISSUE THREAD

**Issue by Spown** [hbenl/vscode-test-explorer#83]
Editor file tabs recognized as tests do not add the usual vertical padding to the top of the file. 

![](https://drive.google.com/uc?id=1Tln4J11ctf-8mCmmTjyDTs5haGTTOr8b)
Left - mocha test file, right - a normal js file.

Thank you.

**Comment by hbenl** [comment]
I can't reproduce this, for me it works for test files as well as other files:
![Screenshot_2019-07-20_14-35-44](https://user-images.githubusercontent.com/16060807/61578755-98e26d80-aafb-11e9-8c59-a3a0ff125db3.png)

**Comment by Spown** [comment]
well, these are my extensions. Do you need some logs?
```
ahebrank.yaml2json
alefragnani.Bookmarks
alefragnani.read-only-indicator
BriteSnow.vscode-toggle-quotes
chrisdias.vscodeZoom
christian-kohler.path-intellisense
dbaeumer.vscode-eslint
dbankier.vscode-quick-select
donjayamanne.githistory
fabiospampinato.vscode-statusbar-debugger
gamunu.vscode-yarn
gerane.Theme-Blackboard
gerane.Theme-PastelsonDark
gerane.Theme-TwoStones
hbenl.vscode-firefox-debug
hbenl.vscode-mocha-test-adapter
hbenl.vscode-test-explorer
HookyQR.beautify
HookyQR.minify
in4margaret.compareit
joelday.docthis
joshpeng.theme-onedark-sublime
mblode.twig-language-2
mhutchie.git-graph
msjsdiag.debugger-for-chrome
nickdodd79.gulptasks
ruakr.vsc-nwjs
samverschueren.yo
slevesque.vscode-autohotkey
vscode-icons-team.vscode-icons
wmaurer.change-case
wmaurer.join-lines
yzane.markdown-pdf
zhuangtongfa.Material-theme
```

**Comment by hbenl** [comment]
I don't think logs would help - I have no idea how my (or any) extension could influence VS Code's behavior in this respect.
You could try disabling all other extensions to see if that makes any difference.
P.S.: I just tested this in Windows as well (my first test was on Linux) and there it also worked for me.

**Comment by Spown** [comment]
Actually it does work now :/. It was reprodusable after complete app reopening, when I made this screenshot. Oh well...
