### ISSUE TITLE
[Question] How do you end debug session?

### ISSUE THREAD

**Issue by Raagh** [hbenl/vscode-test-explorer#85]
I am trying to implement debug feature on my Angular Adapter, I am debugging correctly but after the test run the debugging sessions stays open. How re you ending this session? I tried finding it on your jasmine adapter but couldn't do it.

**Comment by hbenl** [comment]
> I tried finding it on your jasmine adapter but couldn't do it.

That's because I don't do anything to end the debug session - it is ended automatically when the process that is being debugged exits. So I guess that something is keeping the child process that is running the tests alive, usually this is an event listener that is registered somewhere.

**Comment by Raagh** [comment]
Ahhh okey that's the think. I don't have any child process for running the tests. The karma server is started when load tests. And the run tests just executes a query on the karma test server. I have to figure out if I can change the run to be a child process....

**Comment by hbenl** [comment]
I forgot that Karma runs the tests in a browser, so you can't run them in a node child process. So since there doesn't seem to be a way for an extension to tell VS Code to end a debug session, the only way would be to close the browser. Is there a way to tell Karma to launch and close the browser for each test run instead of keeping it running?

**Comment by Raagh** [comment]
yes there is(there is a configuration in karma to stop everything after each run), unfortunately that would slow down the explorer a lot. every time I launch karma everything needs to be build by webpack and angular and then served to karma. This process is very slow so until now I was doing this only on loadTests and then keep the instance open for running them. That was the original idea... I am gonna see if there is a way to close the browser without killing karma but I don't think that's possible.

**Comment by hbenl** [comment]
In that case it may be more practical to just tell users that they have to stop the debug session manually...

**Comment by Raagh** [comment]
yeah I might have to do that. I am gonna try a few things first. It really sucks to deliver a half baked feature but since this is an integration sometimes you just to deal with this stuff. Thank you very much for your help. I am very close to finishing all important features on the explorer :)
