### ISSUE TITLE
[Question] How to add new tests or suite of tests to the ui without reloading everything?

### ISSUE THREAD

**Issue by Raagh** [hbenl/vscode-test-explorer#89]
Hey man I am back asking annoying questions. So here is the thing, could you explain me how you add new tests to the ui when the user adds a new test in a file? the same if he adds a completely new file. I am getting those tests from my test enviroment but I am not able to add them to the test explorer UI without triggering a full reload.

**Comment by hbenl** [comment]
You can only send the full test tree to Test Explorer. If you don't want to do a full reload, you should keep a copy of the test tree (i.e. `TestLoadFinishedEvent#suite`) in your adapter, add the new tests to that and then send a `TestLoadStartedEvent` followed by a `TestLoadFinishedEvent` containing the updated test tree.

**Comment by Raagh** [comment]
yeah you re right my bad, I was doing that but I was using an eventEmitter without registering it in the disposable collection, that's why it wasn't working. Now I need to implement some kind of logic to only load if something changes(cause karma returns all the files every single time even if you re just running the tests). Thanks :)
