### ISSUE TITLE
[Discussion] Explore adding support for VS Live Share

### ISSUE THREAD

**Issue by lostintangent** [hbenl/vscode-test-explorer#9]
[VS Live Share](aka.ms) allows devs to collaborate with others in real time, directly from within VS Code. All of the “guests” that join a Live Share session are remotely connecting to the “host” (the person who shared), and can edit, debug, access terminals (if allowed), run tasks, etc. without needing to download any files or setup their environment.

Because “guests” are pulling their state from the “host”, and don’t have local file access, certain extensions (like this one!) don’t work out of the box. However, we just [published an API](https://www.npmjs.com/package/vsls#messaging-rpc) that allows extensions to detect the presence of a Live Share session, and then use the secure connection that is established between all participants. You can then use this to send RPC messages, such as retrieving the list of tests from the host, requesting to run a test, etc.

It would be cool to explore an integration between this extension and Live Share, in order to allow tests to be collaboratively viewed and run (which is a common feature request for us!). We need to enable automatically syncing output channels (so that test results would be transparently shared), to fully complete this scenario. But I’d be curious to hear if this kind of integration would be interesting or not. Thanks!

**Comment by hbenl** [comment]
This does indeed sound interesting!
I'm not sure yet how this would be implemented exactly, but I don't see a reason why it shouldn't be possible.
I imagine that syncing output channels wouldn't even be needed - the test results would be displayed in the Test Explorer on the guest side just like results from any other Test Adapter.

**Comment by lostintangent** [comment]
@hbenl Ah that’s true. If the underlying state/model that maintains the list of tests and their status is already well separated from the UI, it should be possible to retrieve it from the host, instead of the local adapters. I’d be happy to help, since I think this could be a really compelling experience!

**Comment by hbenl** [comment]
[Done](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer-liveshare)
