### ISSUE TITLE
Tests not found in explorer if project folder name contains spaces

### ISSUE THREAD

**Issue by yaagma** [hbenl/vscode-test-explorer#91]
If I have a project called "Project A", the Test Explorer panel doesn't find any test. If I rename the project folder to "ProjectA" (remove the space), everything works ok.

Even if the project folder name has _no_ spaces, _**but any**_ of its _**parents**_ folders names has, tests are not found.
For example, I have all my projects in "My Projects" and I can't use this extension in any of them (it doesn't matter how they are called because its parent name has spaces).

I'm using Windows 10.
Thanks
Ps: Excuse my English.

**Comment by AlexHaxe** [comment]
You haven't said what test adapter or what test framework you use, I would assume your problem is caused by that rather than test explorer. 
e.g. with Haxe's test adapter I can run tests inside a folder with spaces and they show up, so it's not that test explorer can't handle spaces.

**Comment by yaagma** [comment]
Sorry. I was talking about Jest Explorer (rtbenfield.vscode-jest-test-adapter).
I have used the wrong Repository. I'll copy my issue to the right one.
Thanks
