### ISSUE TITLE
Debug from Test Explorer UI broken for VSCode 1.37.1

### ISSUE THREAD

**Issue by rhymu8354** [hbenl/vscode-test-explorer#93]
Test Explorer UI version: 2.14.4

VSCode info:

> Version: 1.37.1 (user setup)
> Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
> Date: 2019-08-15T16:17:55.855Z
> Electron: 4.2.7
> Chrome: 69.0.3497.128
> Node.js: 10.11.0
> V8: 6.9.427.31-electron.0
> OS: Windows_NT x64 10.0.17134

The "debug" button, either in the Test Explorer UI panel itself or above the test, does not do anything.  To get it to work, I had to revert back to version 2.14.3.

I took a look at the commit you added to support VSCode 1.38.  I think this change broke backwards compatibility, so it won't work for VSCode 1.37.1 or earlier.  I'm sorry I don't understand the code well enough to recommend a fix.

**Comment by hbenl** [comment]
Sorry about that, it's fixed in 2.14.5.
