### ISSUE TITLE
Consider adding a double click action for a tree item to go to the source

### ISSUE THREAD

**Issue by kondratyev-nv** [hbenl/vscode-test-explorer#97]
In my test adapter, I've received an improvement request to add a double-click action for tree items to navigate to the test source code - https://github.com/kondratyev-nv/vscode-python-test-adapter/issues/106. It looks like that test adapters can not add such behavior. However, I think this can be a nice feature to have. So I would like to ask if this is possible and what do you think of it.

**Comment by AlexHaxe** [comment]
Do you mean in addition to the "Show Source" icon that appears when you hover over a test?

**Comment by kondratyev-nv** [comment]
I will close the issue, sorry bothering you. I didn't find any way to add double-click actions from the TreeView items of VSCode itself. Also, I looked through the code of Test Explorer UI, and I think adding such functionality for single-click would be inconvenient for users.

**Comment by Gama11** [comment]
It's possible to have double-click actions, you just have to implement them / the double click delay yourself. [Here's](https://github.com/vshaxe/vshaxe/blob/7c5c6e78dba9b7932eb6c715b64d1645b934d4da/src/vshaxe/view/dependencies/DependencyTreeView.hx#L226) an example.
