### ISSUE TITLE
Individual tests stuck in "loading" state.

### ISSUE THREAD

**Issue by valerierose** [hbenl/vscode-test-explorer#99]
Since I updated VSCode last, I've had this issue which makes it easier to just run tests the old way, without the plugin.

Steps to reproduce:

Run all tests with the "play" button at the top.
Rerun an individual failing test with the "play" button for that test.
Expected behavior:

The "X" icon turns to a loading indicator while the test is running.
Then the icon turns to an "X" or a checkmark depending on the outcome.
Other tests continue to update as they are run.
Actual behavior:

The entire sidebar UI is stuck with the loading indicator on the first individual test that was rerun.
Unable to run groups of tests -- the play buttons don't appear when hovering.
Here's what's in my "About Visual Studio Code":
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:00.827Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 15.6.0

**Comment by hbenl** [comment]
According to the discussion in kondratyev-nv/vscode-python-test-adapter#109, this seems to be an issue with a different extension.
